/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/dashboard': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * ダッシュボードを取得する
     * @description 不合格・注意を先頭に並べる。開く目的が「問題があるか確認すること」であるため。
     */
    get: operations['dashboard']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** ログイン中の利用者とロールを返す */
    get: operations['me']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/runs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Run を作成する
     * @description 計測開始時に呼ぶ。同一コミットへの再送信は attempt を増やした新しい Run になる。
     */
    post: operations['createRun']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/runs/{runId}/artifacts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * 成果物をアップロードする
     * @description この時点ではパースしない。受領・検証・保存のみを行い、パースは判定ジョブで実施する。
     */
    post: operations['uploadArtifact']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/runs/{runId}/finalize': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * 取り込み完了を宣言する
     * @description 判定は非同期で開始される。CI は判定の完了を待たずに次へ進んでよい。
     */
    post: operations['finalizeRun']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/runs/{runId}/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 処理状態と判定結果を取得する（CI のポーリング用） */
    get: operations['status']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    Alert: {
      code?: string
      message?: string
      /** Format: uuid */
      repositoryId?: string
    }
    /** @description Run の作成要求。CI が計測開始時に送信する。 */
    CreateRunRequest: {
      /** @description 差分計測の比較基準。省略時は quality-gate が merge-base を解決する */
      baseCommitSha?: string
      branch: string
      ciRunUrl?: string
      /** @description 計測対象のコミット SHA（40 桁） */
      commitSha: string
      /** Format: date-time */
      measuredAt: string
      /** Format: int32 */
      pullRequestNumber?: number
      /**
       * @description owner/name 形式。Ingest Token の発行元と一致する必要がある
       * @example ymiyamoto63/quality-gate
       */
      repository: string
      /**
       * @description 計測を実行したランナー種別。性能指標の判定可否がこれで決まる
       * @enum {string}
       */
      runnerType: 'self-hosted' | 'github-hosted'
      /** @description CI が実行しなかった指標の申告。省略時は全指標を計測したものとして扱う */
      skippedMetrics?: components['schemas']['SkippedMetricRequest'][]
      triggeredBy: string
    }
    CreateRunResponse: {
      /** Format: int32 */
      attempt?: number
      /** @description Run 詳細画面への直リンク。CI のログに出して、不合格時にその場から飛べるようにする */
      detailUrl?: string
      /** Format: uuid */
      runId?: string
      /** @enum {string} */
      status?:
        'CREATED' | 'UPLOADING' | 'FINALIZED' | 'PROCESSING' | 'EVALUATED' | 'FAILED' | 'ABANDONED'
    }
    /** @description ダッシュボード。repository_summaries を読むだけで応答する。 */
    DashboardResponse: {
      /** @description 計測途絶などの警告。画面側で判定させず、サーバが返す */
      alerts?: components['schemas']['Alert'][]
      repositories?: components['schemas']['RepositoryCard'][]
    }
    FinalizeResponse: {
      detailUrl?: string
      /** Format: uuid */
      runId?: string
      /** @enum {string} */
      status?:
        'CREATED' | 'UPLOADING' | 'FINALIZED' | 'PROCESSING' | 'EVALUATED' | 'FAILED' | 'ABANDONED'
    }
    /** @description データの鮮度。基準日数は設定値のため、判定結果をサーバが返す。 */
    Freshness: {
      /** Format: date-time */
      lastFullMeasuredAt?: string
      /** Format: date-time */
      lastMeasuredAt?: string
      staleFullMeasurement?: boolean
      staleMeasurement?: boolean
    }
    LatestRun: {
      /** @enum {string} */
      completeness?: 'FULL' | 'PARTIAL'
      /** Format: date-time */
      measuredAt?: string
      /** Format: uuid */
      runId?: string
      /**
       * @description 判定結果。未判定なら null
       * @enum {string}
       */
      verdict?: 'PASS' | 'PASS_WITH_WARNINGS' | 'FAIL'
    }
    /** @description ログイン中の利用者。フロントエンドはこの role で表示を制御する（防御は API 側）。 */
    MeResponse: {
      avatarUrl?: string
      displayName?: string
      githubLogin?: string
      /** @enum {string} */
      role?: 'ADMIN' | 'VIEWER'
      /** Format: uuid */
      userId?: string
    }
    RepositoryCard: {
      /** Format: int32 */
      activeWaiverCount?: number
      freshness?: components['schemas']['Freshness']
      fullName?: string
      latestRun?: components['schemas']['LatestRun']
      /** Format: int32 */
      openCriticalCount?: number
      /** Format: int32 */
      openHighCount?: number
      /** Format: uuid */
      repositoryId?: string
    }
    /** @description CI がポーリングするための軽量な状態応答。 */
    RunStatusResponse: {
      /** @enum {string} */
      completeness?: 'FULL' | 'PARTIAL'
      detailUrl?: string
      errorCode?: string
      /** Format: uuid */
      runId?: string
      /** @enum {string} */
      status?:
        'CREATED' | 'UPLOADING' | 'FINALIZED' | 'PROCESSING' | 'EVALUATED' | 'FAILED' | 'ABANDONED'
      /**
       * @description 判定結果。未判定の場合は null
       * @enum {string}
       */
      verdict?: 'PASS' | 'PASS_WITH_WARNINGS' | 'FAIL'
    }
    /** @description スキップの申告。申告のない未提出は ERROR として扱われる。 */
    SkippedMetricRequest: {
      /** @example M-02 */
      metricId: string
      /**
       * @description なぜ計測しなかったか。Run 詳細にそのまま表示される
       * @example GitHub ホストランナーのため PIT を実行しない
       */
      reason: string
    }
    UploadArtifactResponse: {
      /** Format: uuid */
      artifactId?: string
      sha256?: string
      /** Format: int64 */
      sizeBytes?: number
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  dashboard: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['DashboardResponse']
        }
      }
    }
  }
  me: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['MeResponse']
        }
      }
    }
  }
  createRun: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateRunRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['CreateRunResponse']
        }
      }
    }
  }
  uploadArtifact: {
    parameters: {
      query: {
        type: string
        component?: string
        scope?: string
        metadata?: string
      }
      header?: never
      path: {
        runId: string
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        'multipart/form-data': {
          /** Format: binary */
          file: string
        }
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['UploadArtifactResponse']
        }
      }
    }
  }
  finalizeRun: {
    parameters: {
      query?: never
      header?: never
      path: {
        runId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['FinalizeResponse']
        }
      }
    }
  }
  status: {
    parameters: {
      query?: never
      header?: never
      path: {
        runId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RunStatusResponse']
        }
      }
    }
  }
}
