/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/audit-logs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 監査ログを新しい順に一覧する */
    get: operations['list_5']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/dashboard': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * ダッシュボードを取得する
     * @description 不合格・注意を先頭に並べる。開く目的が「問題があるか確認すること」であるため。
     */
    get: operations['dashboard']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ingest-tokens/{tokenId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Ingest Token を失効させる（即座に無効になる） */
    delete: operations['revoke_1']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/jobs/dead': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 恒久的に失敗したジョブを一覧する（新しい順に最大 100 件） */
    get: operations['deadJobs']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/jobs/{jobId}/retry': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 恒久的に失敗したジョブを再実行する */
    post: operations['retry']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** ログイン中の利用者とロールを返す */
    get: operations['me']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/reports': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 品質レポートを取得する
     * @description 期間内に判定された既定ブランチの Run を、リポジトリごとにまとめる。期間を省略すると今日までの 30 日間。リポジトリを省略すると有効なリポジトリすべて
     */
    get: operations['report']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/reports/measurements.csv': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 品質レポートの明細を CSV で取得する
     * @description 1 行が「Run × 指標（コンポーネント・計測条件）」。UTF-8（BOM つき）。条件はレポートと同じ
     */
    get: operations['csv']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/repositories': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 登録済みのリポジトリを一覧する */
    get: operations['list_4']
    put?: never
    /** リポジトリを登録する */
    post: operations['create_1']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/repositories/{repositoryId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * リポジトリ詳細を取得する
     * @description 指標の表は latestRun の Run 詳細（GET /api/v1/runs/{runId}）から描く。判定表の組み立てを 2 箇所に持たないため。
     */
    get: operations['detail']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** リポジトリの設定を更新する（既定ブランチ・PR 計測・有効/無効） */
    patch: operations['update_3']
    trace?: never
  }
  '/api/v1/repositories/{repositoryId}/components': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** コンポーネントを定義する（同名があれば置き換える） */
    post: operations['defineComponent']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/repositories/{repositoryId}/config': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 現在の設定と版の履歴、直近の検証結果を取得する
     * @description 検証エラーは行番号とキーのパス付きで返す。書いた人が自力で直せるように。
     */
    get: operations['get_1']
    /**
     * UI から設定を更新する
     * @description CI が送ったファイルが優先される。直近に判定された Run がファイルの設定で判定されている場合は 409 CONFIG_MANAGED_BY_FILE。検証エラーは 422 CONFIG_VALIDATION_FAILED（行番号付き）。
     */
    put: operations['update_1']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/repositories/{repositoryId}/config/dry-run': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * 設定の変更を過去の Run で試算する（ドライラン）
     * @description 既定ブランチで判定された直近の Run を、保存前の設定で判定し直した結果を返す（FR-02-5）。何も保存しない。検証エラーは 422 CONFIG_VALIDATION_FAILED（行番号付き）。
     */
    post: operations['dryRun']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/repositories/{repositoryId}/ingest-tokens': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 発行済みの Ingest Token を一覧する（平文は返さない） */
    get: operations['tokens']
    put?: never
    /**
     * Ingest Token を発行する
     * @description token（平文）はこの応答でのみ返す。以後どの API からも取得できない。
     */
    post: operations['issue']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/repositories/{repositoryId}/notification-settings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 通知設定を取得する */
    get: operations['get']
    /**
     * 通知設定を更新する
     * @description 変更は監査ログに残す。
     */
    put: operations['update']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/repositories/{repositoryId}/trends': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 指標の時系列を取得する
     * @description 計測環境ごとに系列を分ける。未計測は値 null の点として返し、0 にしない。
     */
    get: operations['trends']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/runs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Run を新しい順に一覧する */
    get: operations['list_2']
    put?: never
    /**
     * Run を作成する
     * @description 計測開始時に呼ぶ。同一コミットへの再送信は attempt を増やした新しい Run になる。
     */
    post: operations['createRun']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/runs/{runId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Run の判定結果を取得する
     * @description 指標はカテゴリごとにまとめて返す。分類規則を画面に持たせない。
     */
    get: operations['detail_1']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/runs/{runId}/artifacts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Run に取り込んだ成果物を一覧する */
    get: operations['list_3']
    put?: never
    /**
     * 成果物をアップロードする
     * @description この時点ではパースしない。受領・検証・保存のみを行い、パースは判定ジョブで実施する。
     */
    post: operations['uploadArtifact']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/runs/{runId}/artifacts/{artifactId}/content': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 成果物をダウンロードする
     * @description 保持期間を過ぎて実体を削除済みなら 409 ARTIFACTS_DELETED。
     */
    get: operations['content']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/runs/{runId}/finalize': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * 取り込み完了を宣言する
     * @description 判定は非同期で開始される。CI は判定の完了を待たずに次へ進んでよい。
     */
    post: operations['finalizeRun']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/runs/{runId}/findings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Run に紐づく違反を一覧する
     * @description state を省略すると新規・継続・初回のみを返す。解消済みは明示指定が必要。
     */
    get: operations['findings']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/runs/{runId}/reevaluate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Run を再評価する
     * @description 保存済みの成果物を読み直し、最新の設定・免除・脆弱性情報で判定し直す。成果物が保持期間を過ぎて削除されていれば 409 ARTIFACTS_DELETED。
     */
    post: operations['reevaluate']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/runs/{runId}/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 処理状態と判定結果を取得する（CI のポーリング用） */
    get: operations['status']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/settings/retention': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** データ保持期間を取得する */
    get: operations['retention']
    /**
     * データ保持期間を変更する
     * @description 翌日の保持期間バッチから効く。短くすると古いデータが削除される。
     */
    put: operations['updateRetention']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 許可リストの利用者を一覧する */
    get: operations['list_1']
    put?: never
    /**
     * 許可リストに利用者を追加する
     * @description GitHub ログイン名の実在は確認しない。存在しない名前はログインできないだけで害がない。
     */
    post: operations['add']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users/{userId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /**
     * ロールの変更・無効化
     * @description 自分自身の降格・無効化と、有効な管理者が 0 人になる変更は 409 ADMIN_REQUIRED。
     */
    patch: operations['update_2']
    trace?: never
  }
  '/api/v1/waivers': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * 免除を一覧する
     * @description 有効なものを期限の近い順に先頭へ並べる。
     */
    get: operations['list']
    put?: never
    /**
     * 免除を登録する
     * @description 理由は 20 文字以上、期限は最長 90 日。登録と同時に最新 Run の再評価を積む。同じ対象に有効な免除があれば 409 WAIVER_ALREADY_EXISTS。
     */
    post: operations['create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/waivers/{waiverId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * 免除を失効させる
     * @description 失効と同時に最新 Run の再評価を積む。
     */
    delete: operations['revoke']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/badges/{owner}/{name}.svg': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 既定ブランチの最新の合否のバッジ（認証不要） */
    get: operations['badge']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    Alert: {
      code?: string
      message?: string
      /** Format: uuid */
      repositoryId?: string
    }
    ArtifactItem: {
      /** Format: uuid */
      artifactId: string
      component: string | null
      /** @description 保持期間を過ぎて実体を削除済みなら true。ダウンロードできない */
      deleted: boolean
      filename: string
      sha256: string
      /** Format: int64 */
      sizeBytes: number
      type: string
      /** Format: date-time */
      uploadedAt: string
    }
    /** @description Run に取り込んだ成果物の一覧（FR-07-5） */
    ArtifactListResponse: {
      items: components['schemas']['ArtifactItem'][]
    }
    AuditLogItem: {
      action: string
      /** @description 日次バッチの操作は system */
      actorLogin: string | null
      /** @description 変更後の値 */
      after: {
        [key: string]: unknown
      } | null
      /** Format: uuid */
      auditLogId: string
      /** @description 変更前の値 */
      before: {
        [key: string]: unknown
      } | null
      /** Format: date-time */
      occurredAt: string
      targetId: string | null
      targetType: string
    }
    /** @description 監査ログ。新しいものから返す */
    AuditLogListResponse: {
      hasMore: boolean
      items: components['schemas']['AuditLogItem'][]
      nextCursor: string | null
    }
    ComponentItem: {
      language: string
      name: string
      pathPatterns: string[]
    }
    ConfigHistoryItem: {
      /** Format: date-time */
      createdAt: string
      /** Format: uuid */
      gateConfigId: string
      sourceCommitSha: string | null
      sourceType: string
      /** Format: int32 */
      version: number
    }
    /** @description 設定ファイルの検証結果。不正なら判定されず、Run は処理失敗になる */
    ConfigValidation: {
      errors: components['schemas']['ValidationErrorItem'][]
      /** @description 検証に失敗した設定ファイルの内容 */
      rawYaml: string | null
      /**
       * Format: uuid
       * @description 検証に失敗した Run
       */
      runId: string | null
      valid: boolean
    }
    ConfigVersion: {
      /** Format: date-time */
      createdAt: string
      /** Format: uuid */
      gateConfigId: string
      parsed: {
        [key: string]: unknown
      }
      rawYaml: string
      sourceCommitSha: string | null
      sourceType: string
      /** Format: int32 */
      version: number
    }
    CreateRepositoryRequest: {
      /** @description 省略時は main */
      defaultBranch?: string | null
      /** @description 省略時は true */
      measurePullRequests?: boolean | null
      name: string
      owner: string
    }
    /** @description Run の作成要求。CI が計測開始時に送信する。 */
    CreateRunRequest: {
      /** @description 差分計測の比較基準。省略時は quality-gate が merge-base を解決する */
      baseCommitSha?: string
      branch: string
      ciRunUrl?: string
      /** @description 計測対象のコミット SHA（40 桁） */
      commitSha: string
      /** Format: date-time */
      measuredAt: string
      /** Format: int32 */
      pullRequestNumber?: number
      /**
       * @description owner/name 形式。Ingest Token の発行元と一致する必要がある
       * @example ymiyamoto63/quality-gate
       */
      repository: string
      /** @description CI が実行しなかった指標の申告。省略時は全指標を計測したものとして扱う */
      skippedMetrics?: components['schemas']['SkippedMetricRequest'][]
      triggeredBy: string
    }
    CreateRunResponse: {
      /** Format: int32 */
      attempt?: number
      /** @description Run 詳細画面への直リンク。CI のログに出して、不合格時にその場から飛べるようにする */
      detailUrl?: string
      /** Format: uuid */
      runId?: string
      /** @enum {string} */
      status?:
        'CREATED' | 'UPLOADING' | 'FINALIZED' | 'PROCESSING' | 'EVALUATED' | 'FAILED' | 'ABANDONED'
    }
    CreateUserRequest: {
      githubLogin: string
      /**
       * @description 省略時は VIEWER
       * @enum {string|null}
       */
      role?: 'ADMIN' | 'VIEWER' | null
    }
    CreateWaiverRequest: {
      /**
       * Format: date-time
       * @description 期限。現在より後、最大 90 日先まで
       */
      expiresAt: string
      /** @description scope=FINDING のとき必須。違反一覧の fingerprint */
      fingerprint?: string | null
      metricId: string
      reason: string
      /** @enum {string} */
      reasonCategory: 'UNREACHABLE' | 'FALSE_POSITIVE' | 'NO_FIX_AVAILABLE' | 'PLANNED'
      /** Format: uuid */
      repositoryId: string
      /** @enum {string} */
      scope: 'FINDING' | 'METRIC'
    }
    /** @description ダッシュボード。repository_summaries を読むだけで応答する。 */
    DashboardResponse: {
      /** @description 計測途絶などの警告。画面側で判定させず、サーバが返す */
      alerts?: components['schemas']['Alert'][]
      repositories?: components['schemas']['RepositoryCard'][]
    }
    DeadJobItem: {
      /** Format: int32 */
      attempts: number
      /** Format: date-time */
      createdAt: string
      dedupKey: string | null
      /** Format: uuid */
      jobId: string
      lastError: string | null
      type: string
      /** Format: date-time */
      updatedAt: string
    }
    DeadJobList: {
      items: components['schemas']['DeadJobItem'][]
    }
    DefineComponentRequest: {
      language: string
      name: string
      pathPatterns: string[]
    }
    /** @description 設定変更のドライラン（FR-02-5） */
    DryRunResponse: {
      /**
       * Format: int32
       * @description 試算した Run の数
       */
      evaluated: number
      /**
       * Format: int32
       * @description 合格 → 不合格に変わる Run の数
       */
      newlyFailing: number
      /**
       * Format: int32
       * @description 不合格 → 合格に変わる Run の数
       */
      newlyPassing: number
      runs: components['schemas']['RunResult'][]
      /** @description 成果物が保持期間で削除されているなど、試算できなかった Run */
      skipped: components['schemas']['SkippedRun'][]
      /**
       * Format: int32
       * @description 判定結果が変わる Run の数
       */
      verdictChanged: number
    }
    FinalizeResponse: {
      detailUrl?: string
      /** Format: uuid */
      runId?: string
      /** @enum {string} */
      status?:
        'CREATED' | 'UPLOADING' | 'FINALIZED' | 'PROCESSING' | 'EVALUATED' | 'FAILED' | 'ABANDONED'
    }
    FindingItem: {
      componentName: string | null
      /** @description ツール固有の付加情報。無ければ空オブジェクト */
      detail: {
        [key: string]: unknown
      }
      filePath: string | null
      /** Format: uuid */
      findingId: string
      /** @description Run をまたいで違反を同定するキー。免除はこの値で違反を指す */
      fingerprint: string
      /** Format: int32 */
      line: number | null
      metricId: string
      metricName: string
      ruleId: string | null
      /** @enum {string} */
      severity: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW' | 'INFO'
      /** @description 該当箇所へのリンク。ホスティング先の URL 形式はサーバが持つ。パスを持たない違反（依存パッケージの脆弱性など）では null */
      sourceUrl: string | null
      /** @enum {string} */
      state: 'NEW' | 'CONTINUING' | 'RESOLVED' | 'INITIAL'
      title: string
      /** @description 判定時に免除されていた場合のみ。免除は解決ではないため画面では薄く表示しない */
      waiver: components['schemas']['Waiver']
    }
    /** @description Run に紐づく違反の一覧 */
    FindingListResponse: {
      hasMore: boolean
      items: components['schemas']['FindingItem'][]
      /** @description 次ページのカーソル。最終ページでは null */
      nextCursor: string | null
      /**
       * Format: uuid
       * @description Run の属するリポジトリ。免除の登録に使う
       */
      repositoryId: string
      /**
       * Format: int64
       * @description 絞り込み後の総件数。件数表示と「全部見た」の判断に使う
       */
      totalCount: number
    }
    /** @description データの鮮度。基準日数は設定値のため、判定結果をサーバが返す。 */
    Freshness: {
      /** Format: date-time */
      lastFullMeasuredAt?: string
      /** Format: date-time */
      lastMeasuredAt?: string
      staleFullMeasurement?: boolean
      staleMeasurement?: boolean
    }
    /** @description 判定に使った設定版。しきい値を変えても過去の Run は当時の判定のまま */
    GateConfigRef: {
      /** Format: uuid */
      gateConfigId: string
      sourceCommitSha: string | null
      sourceType: string | null
      /** Format: int32 */
      version: number | null
    }
    IssueTokenRequest: {
      /** @description 用途のメモ（例: GitHub Actions） */
      description?: string | null
    }
    /** @description 発行した Ingest Token。token は<strong>この応答でのみ</strong>返す */
    IssuedToken: {
      /** Format: date-time */
      createdAt: string
      /** @description 平文のトークン。以後どの API からも取得できない */
      token: string
      /** Format: uuid */
      tokenId: string
      tokenPrefix: string
    }
    LatestRun: {
      commitSha: string
      /** Format: date-time */
      measuredAt: string
      /** Format: uuid */
      runId: string
      /** @enum {string} */
      verdict: 'PASS' | 'PASS_WITH_WARNINGS' | 'FAIL'
    }
    LatestRunSummary: {
      branch: string
      commitSha: string
      /** @enum {string|null} */
      completeness: 'FULL' | 'PARTIAL' | null
      /** Format: date-time */
      measuredAt: string
      /** Format: uuid */
      runId: string
      /** @enum {string} */
      status:
        'CREATED' | 'UPLOADING' | 'FINALIZED' | 'PROCESSING' | 'EVALUATED' | 'FAILED' | 'ABANDONED'
      /** @enum {string|null} */
      verdict: 'PASS' | 'PASS_WITH_WARNINGS' | 'FAIL' | null
    }
    /** @description ログイン中の利用者。フロントエンドはこの role で表示を制御する（防御は API 側）。 */
    MeResponse: {
      avatarUrl?: string
      displayName?: string
      githubLogin?: string
      /** @enum {string} */
      role?: 'ADMIN' | 'VIEWER'
      /** Format: uuid */
      userId?: string
    }
    MetricChange: {
      componentName: string | null
      /**
       * @description 現在の状態。現在は判定されていない指標なら null
       * @enum {string|null}
       */
      currentStatus:
        'PASS' | 'WARN' | 'FAIL' | 'SKIP' | 'REFERENCE' | 'ERROR' | 'NOT_APPLICABLE' | null
      metricId: string
      reason: string | null
      /** @enum {string} */
      simulatedStatus: 'PASS' | 'WARN' | 'FAIL' | 'SKIP' | 'REFERENCE' | 'ERROR' | 'NOT_APPLICABLE'
      unit: string | null
      value: number | null
    }
    MetricRow: {
      /** @description 最新の値 − 最初の値 */
      change: number | null
      componentName: string | null
      /** @description 期間内で最初の Run の値（同じコンポーネント・条件） */
      firstValue: number | null
      metricId: string
      name: string
      /** @enum {string} */
      status: 'PASS' | 'WARN' | 'FAIL' | 'SKIP' | 'REFERENCE' | 'ERROR' | 'NOT_APPLICABLE'
      unit: string | null
      value: number | null
      /** @description 計測条件（全量 / 変更範囲、計測環境など） */
      variant: string | null
    }
    /** @description 通知設定。通知はメールで送る */
    NotificationSettingsResponse: {
      /** @enum {string} */
      condition: 'EVERY_RUN' | 'TRANSITION' | 'FAIL_ONLY' | 'DISABLED'
      /** @description サーバに SMTP が設定されているか。false ならメールは届かない */
      emailAvailable: boolean
      emailRecipients: string[]
      /** Format: date-time */
      updatedAt: string | null
    }
    /** @description 再評価を受け付けた。判定は非同期で行う */
    ReevaluateResponse: {
      /** Format: uuid */
      jobId: string
      /** Format: uuid */
      runId: string
      /**
       * @description 受付時点の Run の状態
       * @enum {string}
       */
      status:
        'CREATED' | 'UPLOADING' | 'FINALIZED' | 'PROCESSING' | 'EVALUATED' | 'FAILED' | 'ABANDONED'
    }
    /** @description 品質レポート（FR-08-4） */
    ReportResponse: {
      /** Format: date */
      from: string
      repositories: components['schemas']['RepositoryReport'][]
      /** Format: date */
      to: string
      /** @description 期間の区切りに使ったタイムゾーン */
      zone: string
    }
    /** @description 登録・更新したリポジトリ */
    RepositoryAdminResponse: {
      defaultBranch: string
      enabled: boolean
      fullName: string
      measurePullRequests: boolean
      /** Format: uuid */
      repositoryId: string
    }
    RepositoryCard: {
      /** Format: int32 */
      activeWaiverCount?: number
      freshness?: components['schemas']['Freshness']
      fullName?: string
      latestRun?: components['schemas']['LatestRun']
      /** Format: int32 */
      openCriticalCount?: number
      /** Format: int32 */
      openHighCount?: number
      /** Format: uuid */
      repositoryId?: string
    }
    /** @description 現在の設定と版の履歴。validation は直近に届いた設定ファイルの検証結果 */
    RepositoryConfig: {
      /** @description 設定版が 1 つも無ければ null（既定値で判定） */
      current: components['schemas']['ConfigVersion']
      /** @description 既定値の YAML。設定版が無いときの表示と UI 編集の初期値 */
      defaultYaml: string
      /** @description UI から編集できるか。直近に判定された Run が .quality-gate.yml の設定で判定されていれば false */
      editable: boolean
      history: components['schemas']['ConfigHistoryItem'][]
      validation: components['schemas']['ConfigValidation']
    }
    /** @description リポジトリ詳細（S-02）。指標の表は latestRunId の Run 詳細から描く */
    RepositoryDetail: {
      /** Format: int32 */
      activeWaiverCount: number
      components: components['schemas']['ComponentItem'][]
      /**
       * Format: int32
       * @description 判定に使われている設定の版。既定値なら null
       */
      configVersion: number | null
      freshness: components['schemas']['RepositoryFreshness']
      /** Format: uuid */
      lastFullRunId: string | null
      /** @description 判定済みの最新 Run。まだ無ければ null */
      latestRun: components['schemas']['LatestRunSummary']
      repository: components['schemas']['RepositoryItem']
    }
    /** @description データの鮮度（FR-06-2 / FR-06-3）。基準日数はサーバが持つ */
    RepositoryFreshness: {
      /** Format: int32 */
      fullMeasurementIntervalDays: number
      /** Format: date-time */
      lastFullMeasuredAt: string | null
      /** Format: date-time */
      lastMeasuredAt: string | null
      staleFullMeasurement: boolean
      staleMeasurement: boolean
    }
    RepositoryItem: {
      /** Format: date-time */
      createdAt: string
      defaultBranch: string
      enabled: boolean
      fullName: string
      measurePullRequests: boolean
      name: string
      owner: string
      /** Format: uuid */
      repositoryId: string
    }
    /** @description 登録済みのリポジトリ。無効化したものも含む */
    RepositoryList: {
      items: components['schemas']['RepositoryItem'][]
    }
    RepositoryRef: {
      fullName: string | null
      /** Format: uuid */
      repositoryId: string
    }
    /** @description 1 リポジトリ分 */
    RepositoryReport: {
      defaultBranch: string
      /** Format: int32 */
      failed: number
      fullName: string
      /** @description 期間内で最新の Run */
      latest: components['schemas']['LatestRun']
      /** @description 最新の Run の指標と、期間の最初の値からの変化 */
      metrics: components['schemas']['MetricRow'][]
      /** @description 合格（警告つきを含む）の割合（%）。Run が無ければ null */
      passRate: number | null
      /** Format: int32 */
      passed: number
      /** Format: int32 */
      passedWithWarnings: number
      /** Format: uuid */
      repositoryId: string
      /**
       * Format: int32
       * @description 期間内に判定された既定ブランチの Run の数
       */
      runs: number
    }
    Request: {
      /** @description 試す .quality-gate.yml の内容 */
      rawYaml: string
      /**
       * Format: int32
       * @description 試算する直近の Run の数（既定 10、最大 30）
       */
      runs?: number | null
    }
    /** @description データ保持期間（日） */
    RetentionSettings: {
      /**
       * Format: int32
       * @description 成果物のファイル実体。既定 90 日
       */
      artifactDays: number
      /**
       * Format: int32
       * @description 監査ログ。既定 730 日。削除は管理ロールのバッチが行う
       */
      auditLogDays: number
      /**
       * Format: int32
       * @description 通知の送信履歴。既定 365 日
       */
      notificationDays: number
      /**
       * Format: int32
       * @description Run・指標値・違反。既定 730 日（2 年）
       */
      runDays: number
    }
    RunCategory: {
      /** @description カテゴリ名（機能テスト など） */
      category: string
      /** @description 不合格・注意を含むカテゴリは画面の初期状態で展開する */
      expandByDefault: boolean
      metrics: components['schemas']['RunMetric'][]
      /**
       * @description カテゴリ内で最も重いステータス
       * @enum {string}
       */
      status: 'PASS' | 'WARN' | 'FAIL' | 'SKIP' | 'REFERENCE' | 'ERROR' | 'NOT_APPLICABLE'
    }
    /** @description Run 1 件の判定結果 */
    RunDetailResponse: {
      /** Format: int32 */
      artifactCount: number
      /** Format: int32 */
      attempt: number
      baseCommitSha: string | null
      /**
       * Format: uuid
       * @description 差分算出に使った比較対象 Run。初回 Run では null
       */
      baselineRunId: string | null
      branch: string
      categories: components['schemas']['RunCategory'][]
      ciRunUrl: string | null
      commitSha: string
      /** @description コミットへのリンク。URL の組み立てはサーバが持つ */
      commitUrl: string | null
      /** @enum {string|null} */
      completeness: 'FULL' | 'PARTIAL' | null
      /** Format: date-time */
      evaluatedAt: string | null
      /** @description 処理そのものが失敗した場合のみ。判定結果 FAIL とは別物 */
      failure: components['schemas']['RunFailure']
      findingSummary: components['schemas']['RunFindingSummary']
      /** @description 判定に使った設定版。既定値で判定した場合は null */
      gateConfig: components['schemas']['GateConfigRef']
      /** Format: date-time */
      measuredAt: string
      /** Format: int32 */
      pullRequestNumber: number | null
      repository: components['schemas']['RepositoryRef']
      /** Format: uuid */
      runId: string
      skippedMetrics: components['schemas']['SkippedMetricView'][]
      /** @enum {string} */
      status:
        'CREATED' | 'UPLOADING' | 'FINALIZED' | 'PROCESSING' | 'EVALUATED' | 'FAILED' | 'ABANDONED'
      /**
       * @description 判定結果。判定前・処理失敗では null
       * @enum {string|null}
       */
      verdict: 'PASS' | 'PASS_WITH_WARNINGS' | 'FAIL' | null
    }
    /** @description 処理失敗の内容。errorCode で分岐し、hint で対処を示す */
    RunFailure: {
      detail: string | null
      errorCode: string | null
      hint: string
      title: string
    }
    /** @description 違反の内訳。解消（RESOLVED）も件数に含めて「直った数」を示す */
    RunFindingSummary: {
      /** Format: int64 */
      continuing: number
      /** Format: int64 */
      initial: number
      /** Format: int64 */
      newCount: number
      /** Format: int64 */
      resolved: number
      /** Format: int64 */
      waived: number
    }
    /** @description Run の一覧。新しいものから返す */
    RunListResponse: {
      hasMore: boolean
      items: components['schemas']['RunSummary'][]
      nextCursor: string | null
    }
    RunMetric: {
      /** @description コンポーネント名（backend / frontend）。全体値の指標では null */
      componentName: string | null
      /** @description 前回比。前回値か今回値が無ければ null */
      delta: number | null
      /** @description 差分が良い方向か。null は前回比なし */
      deltaImproved: boolean | null
      detail: {
        [key: string]: unknown
      } | null
      /**
       * Format: int64
       * @description この指標に紐づく未解消の違反件数
       */
      findingCount: number
      metricId: string
      name: string
      previousValue: number | null
      /** @description 判定理由。文言はサーバが持ち、画面はそのまま表示する */
      reason: string | null
      /** @enum {string} */
      status: 'PASS' | 'WARN' | 'FAIL' | 'SKIP' | 'REFERENCE' | 'ERROR' | 'NOT_APPLICABLE'
      /** @description 合格ライン。例: {"operator": ">=", "value": 75} */
      threshold: {
        [key: string]: unknown
      } | null
      unit: string | null
      /** @description 実測値。未計測は null。0 は「計測して 0 だった」を意味し別物 */
      value: number | null
      /** @description 計測条件（M-02 の実行範囲 changed / all など）。前回値は条件の一致する Run の値だけを使う。条件の区別が無い指標では null */
      variant: string | null
      /** @description 計測条件の表示名（変更範囲 / 全量 など） */
      variantLabel: string | null
    }
    RunResult: {
      /** @description 判定（合否または指標の状態）が変わる指標だけを並べる */
      changes: components['schemas']['MetricChange'][]
      commitSha: string
      /** @enum {string} */
      currentVerdict: 'PASS' | 'PASS_WITH_WARNINGS' | 'FAIL'
      /** Format: date-time */
      measuredAt: string
      /** Format: uuid */
      runId: string
      /** @enum {string} */
      simulatedVerdict: 'PASS' | 'PASS_WITH_WARNINGS' | 'FAIL'
    }
    /** @description CI がポーリングするための軽量な状態応答。 */
    RunStatusResponse: {
      /** @enum {string} */
      completeness?: 'FULL' | 'PARTIAL'
      detailUrl?: string
      errorCode?: string
      /** Format: uuid */
      runId?: string
      /** @enum {string} */
      status?:
        'CREATED' | 'UPLOADING' | 'FINALIZED' | 'PROCESSING' | 'EVALUATED' | 'FAILED' | 'ABANDONED'
      /**
       * @description 判定結果。未判定の場合は null
       * @enum {string}
       */
      verdict?: 'PASS' | 'PASS_WITH_WARNINGS' | 'FAIL'
    }
    RunSummary: {
      branch: string
      commitSha: string
      /** @enum {string|null} */
      completeness: 'FULL' | 'PARTIAL' | null
      /** Format: date-time */
      evaluatedAt: string | null
      /** Format: date-time */
      measuredAt: string
      /** Format: int32 */
      pullRequestNumber: number | null
      /** Format: uuid */
      runId: string
      /** @enum {string} */
      status:
        'CREATED' | 'UPLOADING' | 'FINALIZED' | 'PROCESSING' | 'EVALUATED' | 'FAILED' | 'ABANDONED'
      /** @enum {string|null} */
      verdict: 'PASS' | 'PASS_WITH_WARNINGS' | 'FAIL' | null
    }
    /** @description スキップの申告。申告のない未提出は ERROR として扱われる。 */
    SkippedMetricRequest: {
      /** @example M-02 */
      metricId: string
      /**
       * @description なぜ計測しなかったか。Run 詳細にそのまま表示される
       * @example PR の計測では PIT を実行しない
       */
      reason: string
    }
    /** @description CI からのスキップ申告。受理されなかった申告も残す */
    SkippedMetricView: {
      /** @description 設定で許容されているか。false なら当該指標は ERROR */
      accepted: boolean
      metricId: string
      name: string
      reason: string
    }
    SkippedRun: {
      reason: string
      /** Format: uuid */
      runId: string
    }
    TokenList: {
      items: components['schemas']['TokenSummary'][]
    }
    /** @description 発行済みのトークン。平文もハッシュも返さない */
    TokenSummary: {
      /** Format: date-time */
      createdAt: string
      description: string | null
      /**
       * Format: date-time
       * @description 一度も使われていなければ null
       */
      lastUsedAt: string | null
      /** Format: date-time */
      revokedAt: string | null
      /** Format: uuid */
      tokenId: string
      tokenPrefix: string
    }
    TrendPoint: {
      commitSha: string
      /** Format: date-time */
      measuredAt: string
      /** Format: uuid */
      runId: string
      /** @enum {string} */
      status: 'PASS' | 'WARN' | 'FAIL' | 'SKIP' | 'REFERENCE' | 'ERROR' | 'NOT_APPLICABLE'
      /** @description 実測値。未計測は null。0 を返さない。0 を返すと、グラフ上で「極めて良い値」に見えてしまう */
      value: number | null
    }
    /** @description 指標の時系列。計測環境ごとに系列を分ける */
    TrendResponse: {
      branch: string
      /** Format: date-time */
      from: string
      metricId: string
      name: string
      series: components['schemas']['TrendSeries'][]
      /** @description 重畳表示する合格ライン。期間内で最後に適用された値。期間中にしきい値が変わった場合は thresholdChanged が true になる */
      threshold: {
        [key: string]: unknown
      } | null
      /** @description 期間内でしきい値が変わったか。true のとき、1 本の線では過去の判定を説明できない */
      thresholdChanged: boolean
      /** Format: date-time */
      to: string
      unit: string | null
    }
    TrendSeries: {
      /** Format: int32 */
      colorIndex: number
      componentName: string | null
      judged: boolean
      label: string
      points: components['schemas']['TrendPoint'][]
      seriesId: string
    }
    UpdateConfigRequest: {
      rawYaml: string
    }
    UpdateNotificationSettingsRequest: {
      /** @enum {string|null} */
      condition?: 'EVERY_RUN' | 'TRANSITION' | 'FAIL_ONLY' | 'DISABLED' | null
      emailRecipients?: string[] | null
    }
    UpdateRepositoryRequest: {
      defaultBranch?: string | null
      /** @description false で無効化（ダッシュボードから外れ、取り込みも拒否される） */
      enabled?: boolean | null
      measurePullRequests?: boolean | null
    }
    UpdateUserRequest: {
      /** @enum {string|null} */
      role?: 'ADMIN' | 'VIEWER' | null
      /** @enum {string|null} */
      status?: 'ACTIVE' | 'DISABLED' | null
    }
    UploadArtifactResponse: {
      /** Format: uuid */
      artifactId?: string
      sha256?: string
      /** Format: int64 */
      sizeBytes?: number
    }
    /** @description 利用者の一覧 */
    UserList: {
      items: components['schemas']['UserResponse'][]
    }
    /** @description 許可リストの利用者。ここに無い GitHub ユーザーはログインできない */
    UserResponse: {
      avatarUrl: string | null
      /** Format: date-time */
      createdAt: string
      /** @description 初回ログインまでは null */
      displayName: string | null
      githubLogin: string
      /**
       * Format: date-time
       * @description 一度もログインしていなければ null
       */
      lastLoginAt: string | null
      /** @enum {string} */
      role: 'ADMIN' | 'VIEWER'
      /** @enum {string} */
      status: 'ACTIVE' | 'DISABLED'
      /** Format: uuid */
      userId: string
    }
    ValidationErrorItem: {
      /**
       * Format: int32
       * @description 1 始まりの行番号
       */
      line: number | null
      message: string
      path: string
    }
    Waiver: {
      /** Format: date */
      expiresOn: string
      reason: string
      /** @enum {string} */
      reasonCategory: 'UNREACHABLE' | 'FALSE_POSITIVE' | 'NO_FIX_AVAILABLE' | 'PLANNED'
      /**
       * @description 現在の状態。判定後に失効・期限切れになっていれば ACTIVE 以外
       * @enum {string}
       */
      status: 'ACTIVE' | 'EXPIRED' | 'REVOKED'
      /** Format: uuid */
      waiverId: string
    }
    /** @description 免除。理由の全文を返す（折りたたむと判断の妥当性を検証できない） */
    WaiverItem: {
      /** Format: date-time */
      createdAt: string
      createdByLogin: string | null
      /** Format: date-time */
      expiresAt: string
      /** @description 期限まで 7 日以内の有効な免除 */
      expiringSoon: boolean
      fingerprint: string | null
      metricId: string
      metricName: string
      reason: string
      /** @enum {string} */
      reasonCategory: 'UNREACHABLE' | 'FALSE_POSITIVE' | 'NO_FIX_AVAILABLE' | 'PLANNED'
      reasonCategoryLabel: string
      repositoryFullName: string
      /** Format: uuid */
      repositoryId: string
      /** Format: date-time */
      revokedAt: string | null
      revokedByLogin: string | null
      /** @enum {string} */
      scope: 'FINDING' | 'METRIC'
      /** @enum {string} */
      status: 'ACTIVE' | 'EXPIRED' | 'REVOKED'
      /** @description 登録時点の違反の見出し */
      title: string | null
      /** Format: uuid */
      waiverId: string
    }
    WaiverList: {
      /**
       * Format: int64
       * @description 有効な免除の件数
       */
      activeCount: number
      /**
       * Format: int64
       * @description 7 日以内に期限切れになる有効な免除の件数
       */
      expiringSoonCount: number
      items: components['schemas']['WaiverItem'][]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  list_5: {
    parameters: {
      query?: {
        /** @description 省略時は to の 30 日前 */
        from?: string
        /** @description 省略時は現在時刻 */
        to?: string
        /** @description 操作種別（WAIVER_CREATED など） */
        action?: string
        limit?: number
        cursor?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['AuditLogListResponse']
        }
      }
    }
  }
  dashboard: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['DashboardResponse']
        }
      }
    }
  }
  revoke_1: {
    parameters: {
      query?: never
      header?: never
      path: {
        tokenId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  deadJobs: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['DeadJobList']
        }
      }
    }
  }
  retry: {
    parameters: {
      query?: never
      header?: never
      path: {
        jobId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  me: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['MeResponse']
        }
      }
    }
  }
  report: {
    parameters: {
      query?: {
        from?: string
        to?: string
        /** @description 対象のリポジトリ（複数指定可） */
        repositoryId?: string[]
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ReportResponse']
        }
      }
    }
  }
  csv: {
    parameters: {
      query?: {
        from?: string
        to?: string
        repositoryId?: string[]
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  list_4: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RepositoryList']
        }
      }
    }
  }
  create_1: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateRepositoryRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RepositoryAdminResponse']
        }
      }
    }
  }
  detail: {
    parameters: {
      query?: never
      header?: never
      path: {
        repositoryId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RepositoryDetail']
        }
      }
    }
  }
  update_3: {
    parameters: {
      query?: never
      header?: never
      path: {
        repositoryId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateRepositoryRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RepositoryAdminResponse']
        }
      }
    }
  }
  defineComponent: {
    parameters: {
      query?: never
      header?: never
      path: {
        repositoryId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['DefineComponentRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  get_1: {
    parameters: {
      query?: never
      header?: never
      path: {
        repositoryId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RepositoryConfig']
        }
      }
    }
  }
  update_1: {
    parameters: {
      query?: never
      header?: never
      path: {
        repositoryId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateConfigRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RepositoryConfig']
        }
      }
    }
  }
  dryRun: {
    parameters: {
      query?: never
      header?: never
      path: {
        repositoryId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Request']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['DryRunResponse']
        }
      }
    }
  }
  tokens: {
    parameters: {
      query?: never
      header?: never
      path: {
        repositoryId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['TokenList']
        }
      }
    }
  }
  issue: {
    parameters: {
      query?: never
      header?: never
      path: {
        repositoryId: string
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['IssueTokenRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['IssuedToken']
        }
      }
    }
  }
  get: {
    parameters: {
      query?: never
      header?: never
      path: {
        repositoryId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['NotificationSettingsResponse']
        }
      }
    }
  }
  update: {
    parameters: {
      query?: never
      header?: never
      path: {
        repositoryId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateNotificationSettingsRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['NotificationSettingsResponse']
        }
      }
    }
  }
  trends: {
    parameters: {
      query: {
        /** @description 指標 ID（M-01 など） */
        metricId: string
        /** @description 省略時はリポジトリの既定ブランチ */
        branch?: string
        /** @description 省略時は to の 30 日前 */
        from?: string
        /** @description 省略時は現在時刻 */
        to?: string
      }
      header?: never
      path: {
        repositoryId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['TrendResponse']
        }
      }
    }
  }
  list_2: {
    parameters: {
      query: {
        repositoryId: string
        limit?: number
        cursor?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RunListResponse']
        }
      }
    }
  }
  createRun: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateRunRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['CreateRunResponse']
        }
      }
    }
  }
  detail_1: {
    parameters: {
      query?: never
      header?: never
      path: {
        runId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RunDetailResponse']
        }
      }
    }
  }
  list_3: {
    parameters: {
      query?: never
      header?: never
      path: {
        runId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ArtifactListResponse']
        }
      }
    }
  }
  uploadArtifact: {
    parameters: {
      query: {
        type: string
        component?: string
        scope?: string
        metadata?: string
      }
      header?: never
      path: {
        runId: string
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        'multipart/form-data': {
          /** Format: binary */
          file: string
        }
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['UploadArtifactResponse']
        }
      }
    }
  }
  content: {
    parameters: {
      query?: never
      header?: never
      path: {
        runId: string
        artifactId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': string
        }
      }
    }
  }
  finalizeRun: {
    parameters: {
      query?: never
      header?: never
      path: {
        runId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['FinalizeResponse']
        }
      }
    }
  }
  findings: {
    parameters: {
      query?: {
        /** @description 指標 ID。複数指定可 */
        metricId?: string[]
        /** @description 省略時は NEW / CONTINUING / INITIAL */
        state?: string[]
        severity?: string[]
        /** @description true=免除中のみ / false=免除でないもののみ / 省略=両方 */
        waived?: boolean
        limit?: number
        cursor?: string
      }
      header?: never
      path: {
        runId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['FindingListResponse']
        }
      }
    }
  }
  reevaluate: {
    parameters: {
      query?: never
      header?: never
      path: {
        runId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ReevaluateResponse']
        }
      }
    }
  }
  status: {
    parameters: {
      query?: never
      header?: never
      path: {
        runId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RunStatusResponse']
        }
      }
    }
  }
  retention: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RetentionSettings']
        }
      }
    }
  }
  updateRetention: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RetentionSettings']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RetentionSettings']
        }
      }
    }
  }
  list_1: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['UserList']
        }
      }
    }
  }
  add: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateUserRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['UserResponse']
        }
      }
    }
  }
  update_2: {
    parameters: {
      query?: never
      header?: never
      path: {
        userId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['UserResponse']
        }
      }
    }
  }
  list: {
    parameters: {
      query?: {
        /** @description 省略時は全リポジトリ */
        repositoryId?: string
        /** @description 省略時はすべての状態 */
        status?: 'ACTIVE' | 'EXPIRED' | 'REVOKED'
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['WaiverList']
        }
      }
    }
  }
  create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateWaiverRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['WaiverItem']
        }
      }
    }
  }
  revoke: {
    parameters: {
      query?: never
      header?: never
      path: {
        waiverId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  badge: {
    parameters: {
      query?: never
      header?: never
      path: {
        owner: string
        name: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'image/svg+xml': string
        }
      }
    }
  }
}
