-- Spring Session JDBC のスキーマ。自動生成に任せず明示的に管理する。
CREATE TABLE SPRING_SESSION (
    PRIMARY_ID            char(36)     NOT NULL,
    SESSION_ID            char(36)     NOT NULL,
    CREATION_TIME         bigint       NOT NULL,
    LAST_ACCESS_TIME      bigint       NOT NULL,
    MAX_INACTIVE_INTERVAL int          NOT NULL,
    EXPIRY_TIME           bigint       NOT NULL,
    PRINCIPAL_NAME        varchar(100),
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);
CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID char(36)     NOT NULL,
    ATTRIBUTE_NAME     varchar(200) NOT NULL,
    ATTRIBUTE_BYTES    bytea        NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID)
        REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);
